export const LOAD_ALL_COMPANY_LIST = 'LOAD_ALL_COMPANY_LIST';
export const LOAD_ALL_COMPANY_LIST_SUCCESS = 'LOAD_ALL_COMPANY_LIST_SUCCESS';
export const LOAD_ALL_COMPANY_LIST_ERROR = 'LOAD_ALL_COMPANY_LIST_ERROR';

export const LOAD_COMPANY_DETAIL = 'LOAD_COMPANY_DETAIL';
export const LOAD_COMPANY_DETAIL_SUCCESS = 'LOAD_COMPANY_DETAIL_SUCCESS';
export const LOAD_COMPANY_DETAIL_ERROR = 'LOAD_COMPANY_DETAIL_ERROR';

export const LOAD_COMPANY_LIST = 'LOAD_COMPANY_LIST';
export const LOAD_COMPANY_LIST_SUCCESS = 'LOAD_COMPANY_LIST_SUCCESS';
export const LOAD_COMPANY_LIST_ERROR = 'LOAD_COMPANY_LIST_ERROR';

export const LOAD_COMPANY_CREATE = 'LOAD_COMPANY_CREATE';
export const LOAD_COMPANY_CREATE_SUCCESS = 'LOAD_COMPANY_CREATE_SUCCESS';
export const LOAD_COMPANY_CREATE_ERROR = 'LOAD_COMPANY_CREATE_ERROR';

export const LOAD_COMPANY_UPDATE = 'LOAD_COMPANY_UPDATE';
export const LOAD_COMPANY_UPDATE_SUCCESS = 'LOAD_COMPANY_UPDATE_SUCCESS';
export const LOAD_COMPANY_UPDATE_ERROR = 'LOAD_COMPANY_UPDATE_ERROR';

export const LOAD_COMPANY_DELETE = 'LOAD_COMPANY_DELETE';
export const LOAD_COMPANY_DELETE_SUCCESS = 'LOAD_COMPANY_DELETE_SUCCESS';
export const LOAD_COMPANY_DELETE_ERROR = 'LOAD_COMPANY_DELETE_ERROR';

export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const LOAD_USER_LIST_SUCCESS = 'LOAD_USER_LIST_SUCCESS';
export const LOAD_USER_LIST_ERROR = 'LOAD_USER_LIST_ERROR';

export const LOAD_USER_DETAIL = 'LOAD_USER_DETAIL';
export const LOAD_USER_DETAIL_SUCCESS = 'LOAD_USER_DETAIL_SUCCESS';
export const LOAD_USER_DETAIL_ERROR = 'LOAD_USER_DETAIL_ERROR';

export const LOAD_USER_CREATE = 'LOAD_USER_CREATE';
export const LOAD_USER_CREATE_SUCCESS = 'LOAD_USER_CREATE_SUCCESS';
export const LOAD_USER_CREATE_ERROR = 'LOAD_USER_CREATE_ERROR';

export const LOAD_USER_UPDATE = 'LOAD_USER_UPDATE';
export const LOAD_USER_UPDATE_SUCCESS = 'LOAD_USER_UPDATE_SUCCESS';
export const LOAD_USER_UPDATE_ERROR = 'LOAD_USER_UPDATE_ERROR';

export const LOAD_USER_DELETE = 'LOAD_USER_DELETE';
export const LOAD_USER_DELETE_SUCCESS = 'LOAD_USER_DELETE_SUCCESS';
export const LOAD_USER_DELETE_ERROR = 'LOAD_USER_DELETE_ERROR';

export const LOAD_LEVEL = 'LOAD_LEVEL';
export const LOAD_LEVEL_SUCCESS = 'LOAD_LEVEL_SUCCESS';
export const LOAD_LEVEL_ERROR = 'LOAD_LEVEL_ERROR';

export const LOAD_LEVEL_ADMIN = 'LOAD_LEVEL_ADMIN';
export const LOAD_LEVEL_ADMIN_SUCCESS = 'LOAD_LEVEL_ADMIN_SUCCESS';
export const LOAD_LEVEL_ADMIN_ERROR = 'LOAD_LEVEL_ADMIN_ERROR';
