export const LOAD_ALIAS_CREATE = 'LOAD_ALIAS_CREATE';
export const LOAD_ALIAS_CREATE_SUCCESS = 'LOAD_ALIAS_CREATE_SUCCESS';
export const LOAD_ALIAS_CREATE_ERROR = 'LOAD_ALIAS_CREATE_ERROR';

export const LOAD_ALIAS_LIST = 'LOAD_ALIAS_LIST';
export const LOAD_ALIAS_LIST_SUCCESS = 'LOAD_ALIAS_LIST_SUCCESS';
export const LOAD_ALIAS_LIST_ERROR = 'LOAD_ALIAS_LIST_ERROR';

export const LOAD_ALIAS_DELETE = 'LOAD_ALIAS_DELETE';
export const LOAD_ALIAS_DELETE_SUCCESS = 'LOAD_ALIAS_DELETE_SUCCESS';
export const LOAD_ALIAS_DELETE_ERROR = 'LOAD_ALIAS_DELETE_ERROR';
