export const LOAD_MEDIA_VISIBILITY = 'LOAD_MEDIA_VISIBILITY';
export const LOAD_MEDIA_VISIBILITY_ERROR = 'LOAD_MEDIA_VISIBILITY_ERROR';
export const LOAD_MEDIA_VISIBILITY_SUCCESS = 'LOAD_MEDIA_VISIBILITY_SUCCESS';

export const LOAD_COVERAGE_TONALITY = 'LOAD_COVERAGE_TONALITY';
export const LOAD_COVERAGE_TONALITY_ERROR = 'LOAD_COVERAGE_TONALITY_ERROR';
export const LOAD_COVERAGE_TONALITY_SUCCESS = 'LOAD_COVERAGE_TONALITY_SUCCESS';

export const LOAD_TRENDING_HIGHLIGHTS = 'LOAD_TRENDING_HIGHLIGHTS';
export const LOAD_TRENDING_HIGHLIGHTS_ERROR = 'LOAD_TRENDING_HIGHLIGHTS_ERROR';
export const LOAD_TRENDING_HIGHLIGHTS_SUCCESS = 'LOAD_TRENDING_HIGHLIGHTS_SUCCESS';

export const LOAD_TONE_CATEGORY = 'LOAD_TONE_CATEGORY';
export const LOAD_TONE_CATEGORY_ERROR = 'LOAD_TONE_CATEGORY_ERROR';
export const LOAD_TONE_CATEGORY_SUCCESS = 'LOAD_TONE_CATEGORY_SUCCESS';

export const LOAD_TONE_MEDIA = 'LOAD_TONE_MEDIA';
export const LOAD_TONE_MEDIA_ERROR = 'LOAD_TONE_MEDIA_ERROR';
export const LOAD_TONE_MEDIA_SUCCESS = 'LOAD_TONE_MEDIA_SUCCESS';

export const LOAD_EWS = 'LOAD_EWS';
export const LOAD_EWS_ERROR = 'LOAD_EWS_ERROR';
export const LOAD_EWS_SUCCESS = 'LOAD_EWS_SUCCESS';

export const LOAD_ANALYTIC_ARTICLE = 'LOAD_ANALYTIC_ARTICLE';
export const LOAD_ANALYTIC_ARTICLE_ERROR = 'LOAD_ANALYTIC_ARTICLE_ERROR';
export const LOAD_ANALYTIC_ARTICLE_SUCCESS = 'LOAD_ANALYTIC_ARTICLE_SUCCESS';

export const LOAD_ANALYTIC_ARTICLE_POSITIVE = 'LOAD_ANALYTIC_ARTICLE_POSITIVE';
export const LOAD_ANALYTIC_ARTICLE_SUCCESS_POSITIVE = 'LOAD_ANALYTIC_ARTICLE_SUCCESS_POSITIVE';

export const LOAD_ANALYTIC_ARTICLE_NEGATIVE = 'LOAD_ANALYTIC_ARTICLE_NEGATIVE';
export const LOAD_ANALYTIC_ARTICLE_SUCCESS_NEGATIVE = 'LOAD_ANALYTIC_ARTICLE_SUCCESS_NEGATIVE';

export const LOAD_ANALYTIC_ARTICLE_NEUTRAL = 'LOAD_ANALYTIC_ARTICLE_NEUTRAL';
export const LOAD_ANALYTIC_ARTICLE_SUCCESS_NEUTRAL = 'LOAD_ANALYTIC_ARTICLE_SUCCESS_NEUTRAL';

export const LOAD_MEDIA_COUNT = 'LOAD_MEDIA_COUNT';
export const LOAD_MEDIA_COUNT_ERROR = 'LOAD_MEDIA_COUNT_ERROR';
export const LOAD_MEDIA_COUNT_SUCCESS = 'LOAD_MEDIA_COUNT_SUCCESS';

// export const LOAD_DOWNLOAD_EXCEL = 'LOAD_DOWNLOAD_EXCEL';
// export const LOAD_DOWNLOAD_EXCEL_ERROR = 'LOAD_DOWNLOAD_EXCEL_ERROR';
// export const LOAD_DOWNLOAD_EXCEL_SUCCESS = 'LOAD_DOWNLOAD_EXCEL_SUCCESS';

// export const LOAD_DOWNLOAD_PDF = 'LOAD_DOWNLOAD_PDF';
// export const LOAD_DOWNLOAD_PDF_ERROR = 'LOAD_DOWNLOAD_PDF_ERROR';
// export const LOAD_DOWNLOAD_PDF_SUCCESS = 'LOAD_DOWNLOAD_PDF_SUCCESS';
