export const LOAD_CONFIG_CATEGORY_LIST = 'LOAD_CONFIG_CATEGORY_LIST';
export const LOAD_CONFIG_CATEGORY_LIST_SUCCESS = 'LOAD_CONFIG_CATEGORY_LIST_SUCCESS';
export const LOAD_CONFIG_CATEGORY_LIST_ERROR = 'LOAD_CONFIG_CATEGORY_LIST_ERROR';

export const LOAD_CONFIG_CATEGORY_CREATE = 'LOAD_CONFIG_CATEGORY_CREATE';
export const LOAD_CONFIG_CATEGORY_CREATE_SUCCESS = 'LOAD_CONFIG_CATEGORY_CREATE_SUCCESS';
export const LOAD_CONFIG_CATEGORY_CREATE_ERROR = 'LOAD_CONFIG_CATEGORY_CREATE_ERROR';

export const LOAD_CONFIG_CATEGORY_UPDATE = 'LOAD_CONFIG_CATEGORY_UPDATE';
export const LOAD_CONFIG_CATEGORY_UPDATE_SUCCESS = 'LOAD_CONFIG_CATEGORY_UPDATE_SUCCESS';
export const LOAD_CONFIG_CATEGORY_UPDATE_ERROR = 'LOAD_CONFIG_CATEGORY_UPDATE_ERROR';

export const LOAD_CONFIG_CATEGORY_DELETE = 'LOAD_CONFIG_CATEGORY_DELETE';
export const LOAD_CONFIG_CATEGORY_DELETE_SUCCESS = 'LOAD_CONFIG_CATEGORY_DELETE_SUCCESS';
export const LOAD_CONFIG_CATEGORY_DELETE_ERROR = 'LOAD_CONFIG_CATEGORY_DELETE_ERROR';

export const LOAD_CONFIG_CATEGORY_DETAIL = 'LOAD_CONFIG_CATEGORY_DETAIL';
export const LOAD_CONFIG_CATEGORY_DETAIL_SUCCESS = 'LOAD_CONFIG_CATEGORY_DETAIL_SUCCESS';
export const LOAD_CONFIG_CATEGORY_DETAIL_ERROR = 'LOAD_CONFIG_CATEGORY_DETAIL_ERROR';

export const LOAD_CONFIG_CATEGORY_ADD_SUBCAT = 'LOAD_CONFIG_CATEGORY_ADD_SUBCAT';
export const LOAD_CONFIG_CATEGORY_ADD_SUBCAT_SUCCESS = 'LOAD_CONFIG_CATEGORY_ADD_SUBCAT_SUCCESS';
export const LOAD_CONFIG_CATEGORY_ADD_SUBCAT_ERROR = 'LOAD_CONFIG_CATEGORY_ADD_SUBCAT_ERROR';

export const LOAD_CONFIG_CATEGORY_CHOSEN = 'LOAD_CONFIG_CATEGORY_CHOSEN';
export const LOAD_CONFIG_CATEGORY_CHOSEN_SUCCESS = 'LOAD_CONFIG_CATEGORY_CHOSEN_SUCCESS';
export const LOAD_CONFIG_CATEGORY_CHOSEN_ERROR = 'LOAD_CONFIG_CATEGORY_CHOSEN_ERROR';
