export const LOAD_CONNECT_UPLOAD = 'LOAD_CONNECT_UPLOAD';
export const LOAD_CONNECT_UPLOAD_ERROR = 'LOAD_CONNECT_UPLOAD_ERROR';
export const LOAD_CONNECT_UPLOAD_SUCCESS = 'LOAD_CONNECT_UPLOAD_SUCCESS';

export const LOAD_CONNECT_MEDIA = 'LOAD_CONNECT_MEDIA';
export const LOAD_CONNECT_MEDIA_ERROR = 'LOAD_CONNECT_MEDIA_ERROR';
export const LOAD_CONNECT_MEDIA_SUCCESS = 'LOAD_CONNECT_MEDIA_SUCCESS';

export const LOAD_CONNECT_MEDIACAT = 'LOAD_CONNECT_MEDIACAT';
export const LOAD_CONNECT_MEDIACAT_ERROR = 'LOAD_CONNECT_MEDIACAT_ERROR';
export const LOAD_CONNECT_MEDIACAT_SUCCESS = 'LOAD_CONNECT_MEDIACAT_SUCCESS';
