export const LOAD_EXCEL_COLUMNS = 'LOAD_EXCEL_COLUMNS';
export const LOAD_EXCEL_COLUMNS_SUCCESS = 'LOAD_EXCEL_COLUMNS_SUCCESS';
export const LOAD_EXCEL_COLUMNS_ERROR = 'LOAD_EXCEL_COLUMNS_ERROR';

export const LOAD_EXCEL_COLUMNS_CREATE = 'LOAD_EXCEL_COLUMNS_CREATE';
export const LOAD_EXCEL_COLUMNS_CREATE_SUCCESS = 'LOAD_EXCEL_COLUMNS_CREATE_SUCCESS';
export const LOAD_EXCEL_COLUMNS_CREATE_ERROR = 'LOAD_EXCEL_COLUMNS_CREATE_ERROR';

export const LOAD_EXCEL_COLUMNS_UPDATE = 'LOAD_EXCEL_COLUMNS_UPDATE';
export const LOAD_EXCEL_COLUMNS_UPDATE_SUCCESS = 'LOAD_EXCEL_COLUMNS_UPDATE_SUCCESS';
export const LOAD_EXCEL_COLUMNS_UPDATE_ERROR = 'LOAD_EXCEL_COLUMNS_UPDATE_ERROR';

export const LOAD_EXCEL_COLUMNS_DELETE = 'LOAD_EXCEL_COLUMNS_DELETE';
export const LOAD_EXCEL_COLUMNS_DELETE_SUCCESS = 'LOAD_EXCEL_COLUMNS_DELETE_SUCCESS';
export const LOAD_EXCEL_COLUMNS_DELETE_ERROR = 'LOAD_EXCEL_COLUMNS_DELETE_ERROR';
