export const LOAD_FILTER = "LOAD_FILTER";

export const LOAD_FILTER_MEDIA = "LOAD_FILTER_MEDIA";
export const LOAD_FILTER_MEDIA_ERROR = "LOAD_FILTER_MEDIA_ERROR";
export const LOAD_FILTER_MEDIA_SUCCESS = "LOAD_FILTER_MEDIA_SUCCESS";

export const LOAD_FILTER_SUB_MEDIA = "LOAD_FILTER_SUB_MEDIA";
export const LOAD_FILTER_SUB_MEDIA_ERROR = "LOAD_FILTER_SUB_MEDIA_ERROR";
export const LOAD_FILTER_SUB_MEDIA_SUCCESS = "LOAD_FILTER_SUB_MEDIA_SUCCESS";

export const LOAD_FILTER_CATEGORY = "LOAD_FILTER_CATEGORY";
export const LOAD_FILTER_CATEGORY_ERROR = "LOAD_FILTER_CATEGORY_ERROR";
export const LOAD_FILTER_CATEGORY_SUCCESS = "LOAD_FILTER_CATEGORY_SUCCESS";

export const LOAD_FILTER_SUB_CATEGORY = "LOAD_FILTER_SUB_CATEGORY";
export const LOAD_FILTER_SUB_CATEGORY_ERROR = "LOAD_FILTER_SUB_CATEGORY_ERROR";
export const LOAD_FILTER_SUB_CATEGORY_SUCCESS = "LOAD_FILTER_SUB_CATEGORY_SUCCESS";
