export const LOAD_GEO = 'LOAD_GEO';
export const LOAD_GEO_SUCCESS = 'LOAD_GEO_SUCCESS';
export const LOAD_GEO_ERROR = 'LOAD_GEO_ERROR';

export const LOAD_GEO_LIST = 'LOAD_GEO_LIST';
export const LOAD_GEO_LIST_SUCCESS = 'LOAD_GEO_LIST_SUCCESS';
export const LOAD_GEO_LIST_ERROR = 'LOAD_GEO_LIST_ERROR';

export const LOAD_GEO_STATUS = 'LOAD_GEO_STATUS';
export const LOAD_GEO_STATUS_SUCCESS = 'LOAD_GEO_STATUS_SUCCESS';
export const LOAD_GEO_STATUS_ERROR = 'LOAD_GEO_STATUS_ERROR';

export const LOAD_GEO_BACKTRACK = 'LOAD_GEO_BACKTRACK';
export const LOAD_GEO_BACKTRACK_SUCCESS = 'LOAD_GEO_BACKTRACK_SUCCESS';
export const LOAD_GEO_BACKTRACK_ERROR = 'LOAD_GEO_BACKTRACK_ERROR';
