export const LOAD_ISSUE_SUMMARY = 'LOAD_ISSUE_SUMMARY';
export const LOAD_ISSUE_SUMMARY_SUCCESS = 'LOAD_ISSUE_SUMMARY_SUCCESS';
export const LOAD_ISSUE_SUMMARY_ERROR = 'LOAD_ISSUE_SUMMARY_ERROR';

export const LOAD_ISSUE_DETAIL = 'LOAD_ISSUE_DETAIL';
export const LOAD_ISSUE_DETAIL_SUCCESS = 'LOAD_ISSUE_DETAIL_SUCCESS';
export const LOAD_ISSUE_DETAIL_ERROR = 'LOAD_ISSUE_DETAIL_ERROR';

export const LOAD_TOPIC_LIST_AUTO = 'LOAD_TOPIC_LIST_AUTO';
export const LOAD_TOPIC_LIST_AUTO_SUCCESS = 'LOAD_TOPIC_LIST_AUTO_SUCCESS';
export const LOAD_TOPIC_LIST_AUTO_ERROR = 'LOAD_TOPIC_LIST_AUTO_ERROR';

export const LOAD_ISSUE_DELETE = 'LOAD_ISSUE_DELETE';
export const LOAD_ISSUE_DELETE_SUCCESS = 'LOAD_ISSUE_DELETE_SUCCESS';
export const LOAD_ISSUE_DELETE_ERROR = 'LOAD_ISSUE_DELETE_ERROR';

export const LOAD_ISSUE_UPDATE = 'LOAD_ISSUE_UPDATE';
export const LOAD_ISSUE_UPDATE_SUCCESS = 'LOAD_ISSUE_UPDATE_SUCCESS';
export const LOAD_ISSUE_UPDATE_ERROR = 'LOAD_ISSUE_UPDATE_ERROR';

export const LOAD_ISSUE_ADD = 'LOAD_ISSUE_ADD';
export const LOAD_ISSUE_ADD_SUCCESS = 'LOAD_ISSUE_ADD_SUCCESS';
export const LOAD_ISSUE_ADD_ERROR = 'LOAD_ISSUE_ADD_ERROR';
