export const LOAD_CONFIG_MEDIA_LIST = 'LOAD_CONFIG_MEDIA_LIST';
export const LOAD_CONFIG_MEDIA_LIST_ERROR = 'LOAD_CONFIG_MEDIA_LIST_ERROR';
export const LOAD_CONFIG_MEDIA_LIST_SUCCESS = 'LOAD_CONFIG_MEDIA_LIST_SUCCESS';

export const LOAD_CONFIG_MEDIA_CHOSEN = 'LOAD_CONFIG_MEDIA_CHOSEN';
export const LOAD_CONFIG_MEDIA_CHOSEN_ERROR = 'LOAD_CONFIG_MEDIA_CHOSEN_ERROR';
export const LOAD_CONFIG_MEDIA_CHOSEN_SUCCESS = 'LOAD_CONFIG_MEDIA_CHOSEN_SUCCESS';

export const LOAD_CONFIG_MEDIA_LIST_CREATE = 'LOAD_CONFIG_MEDIA_LIST_CREATE';
export const LOAD_CONFIG_MEDIA_LIST_CREATE_ERROR = 'LOAD_CONFIG_MEDIA_LIST_CREATE_ERROR';
export const LOAD_CONFIG_MEDIA_LIST_CREATE_SUCCESS = 'LOAD_CONFIG_MEDIA_LIST_CREATE_SUCCESS';

export const LOAD_CONFIG_MEDIA_LIST_UPDATE = 'LOAD_CONFIG_MEDIA_LIST_UPDATE';
export const LOAD_CONFIG_MEDIA_LIST_UPDATE_ERROR = 'LOAD_CONFIG_MEDIA_LIST_UPDATE_ERROR';
export const LOAD_CONFIG_MEDIA_LIST_UPDATE_SUCCESS = 'LOAD_CONFIG_MEDIA_LIST_UPDATE_SUCCESS';

export const LOAD_CONFIG_MEDIA_LIST_DELETE = 'LOAD_CONFIG_MEDIA_LIST_DELETE';
export const LOAD_CONFIG_MEDIA_LIST_DELETE_ERROR = 'LOAD_CONFIG_MEDIA_LIST_DELETE_ERROR';
export const LOAD_CONFIG_MEDIA_LIST_DELETE_SUCCESS = 'LOAD_CONFIG_MEDIA_LIST_DELETE_SUCCESS';

export const LOAD_CONFIG_MEDIA_CHOSEN_UPDATE = 'LOAD_CONFIG_MEDIA_CHOSEN_UPDATE';
export const LOAD_CONFIG_MEDIA_CHOSEN_UPDATE_ERROR = 'LOAD_CONFIG_MEDIA_CHOSEN_UPDATE_ERROR';
export const LOAD_CONFIG_MEDIA_CHOSEN_UPDATE_SUCCESS = 'LOAD_CONFIG_MEDIA_CHOSEN_UPDATE_SUCCESS';

export const LOAD_CONFIG_MEDIA_DETAIL = 'LOAD_CONFIG_MEDIA_DETAIL';
export const LOAD_CONFIG_MEDIA_DETAIL_ERROR = 'LOAD_CONFIG_MEDIA_DETAIL_ERROR';
export const LOAD_CONFIG_MEDIA_DETAIL_SUCCESS = 'LOAD_CONFIG_MEDIA_LIST_SUCCESS';
