export const LOAD_NEWS_CLIPPING = 'LOAD_NEWS_CLIPPING';
export const LOAD_NEWS_CLIPPING_ERROR = 'LOAD_NEWS_CLIPPING_ERROR';
export const LOAD_NEWS_CLIPPING_SUCCESS = 'LOAD_NEWS_CLIPPING_SUCCESS';

export const LOAD_NEWS_CLIPPING_SEND_EMAIL = 'LOAD_NEWS_CLIPPING_SEND_EMAIL';
export const LOAD_NEWS_CLIPPING_SEND_EMAIL_ERROR = 'LOAD_NEWS_CLIPPING_SEND_EMAIL_ERROR';
export const LOAD_NEWS_CLIPPING_SEND_EMAIL_SUCCESS = 'LOAD_NEWS_CLIPPING_SEND_EMAIL_SUCCESS';

export const LOAD_NEWS_CLIPPING_DOCXS = 'LOAD_NEWS_CLIPPING_DOCXS';
export const LOAD_NEWS_CLIPPING_DOCXS_ERROR = 'LOAD_NEWS_CLIPPING_DOCXS_ERROR';
export const LOAD_NEWS_CLIPPING_DOCXS_SUCCESS = 'LOAD_NEWS_CLIPPING_DOCXS_SUCCESS';

export const LOAD_NEWS_CLIPPING_PDF = 'LOAD_NEWS_CLIPPING_PDF';
export const LOAD_NEWS_CLIPPING_PDF_ERROR = 'LOAD_NEWS_CLIPPING_PDF_ERROR';
export const LOAD_NEWS_CLIPPING_PDF_SUCCESS = 'LOAD_NEWS_CLIPPING_PDF_SUCCESS';

// >>>>>>>>>>>> SPONSORSHIP <<<<<<<<<<

export const LOAD_SPONSOR = 'LOAD_SPONSOR';
export const LOAD_SPONSOR_ERROR = 'LOAD_SPONSOR_ERROR';
export const LOAD_SPONSOR_SUCCESS = 'LOAD_SPONSOR_SUCCESS';

export const LOAD_SPONSOR_ADD = 'LOAD_SPONSOR_ADD';
export const LOAD_SPONSOR_ADD_ERROR = 'LOAD_SPONSOR_ADD_ERROR';
export const LOAD_SPONSOR_ADD_SUCCESS = 'LOAD_SPONSOR_ADD_SUCCESS';

export const LOAD_SPONSOR_UPDATE = 'LOAD_SPONSOR_UPDATE';
export const LOAD_SPONSOR_UPDATE_ERROR = 'LOAD_SPONSOR_UPDATE_ERROR';
export const LOAD_SPONSOR_UPDATE_SUCCESS = 'LOAD_SPONSOR_UPDATE_SUCCESS';

export const LOAD_SPONSOR_DELETE = 'LOAD_SPONSOR_DELETE';
export const LOAD_SPONSOR_DELETE_ERROR = 'LOAD_SPONSOR_DELETE_ERROR';
export const LOAD_SPONSOR_DELETE_SUCCESS = 'LOAD_SPONSOR_DELETE_SUCCESS';

export const LOAD_SPONSOR_ARTICLE_ADD = 'LOAD_SPONSOR_ARTICLE_ADD'; // add or update sponsor article
export const LOAD_SPONSOR_ARTICLE_ADD_ERROR = 'LOAD_SPONSOR_ARTICLE_ADD_ERROR';
export const LOAD_SPONSOR_ARTICLE_ADD_SUCCESS = 'LOAD_SPONSOR_ARTICLE_ADD_SUCCESS';

export const LOAD_SPONSOR_ARTICLE_DELETE = 'LOAD_SPONSOR_ARTICLE_DELETE';
export const LOAD_SPONSOR_ARTICLE_DELETE_ERROR = 'LOAD_SPONSOR_ARTICLE_DELETE_ERROR';
export const LOAD_SPONSOR_ARTICLE_DELETE_SUCCESS = 'LOAD_SPONSOR_ARTICLE_DELETE_SUCCESS';

// >>>>>>>>>>>> EDITING <<<<<<<<<<

export const LOAD_NEWS_CLIPPING_UPDATE_TITLE = 'LOAD_NEWS_CLIPPING_UPDATE_TITLE';
export const LOAD_NEWS_CLIPPING_UPDATE_TITLE_ERROR = 'LOAD_NEWS_CLIPPING_UPDATE_TITLE_ERROR';
export const LOAD_NEWS_CLIPPING_UPDATE_TITLE_SUCCESS = 'LOAD_NEWS_CLIPPING_UPDATE_TITLE_SUCCESS';

export const LOAD_NEWS_CLIPPING_UPDATE_SUMMARY = 'LOAD_NEWS_CLIPPING_UPDATE_SUMMARY';
export const LOAD_NEWS_CLIPPING_UPDATE_SUMMARY_ERROR = 'LOAD_NEWS_CLIPPING_UPDATE_SUMMARY_ERROR';
export const LOAD_NEWS_CLIPPING_UPDATE_SUMMARY_SUCCESS = 'LOAD_NEWS_CLIPPING_UPDATE_SUMMARY_SUCCESS';

export const LOAD_NEWS_CLIPPING_UPDATE_TONE = 'LOAD_NEWS_CLIPPING_UPDATE_TONE';
export const LOAD_NEWS_CLIPPING_UPDATE_TONE_ERROR = 'LOAD_NEWS_CLIPPING_UPDATE_TONE_ERROR';
export const LOAD_NEWS_CLIPPING_UPDATE_TONE_SUCCESS = 'LOAD_NEWS_CLIPPING_UPDATE_TONE_SUCCESS';

export const LOAD_NEWS_CLIPPING_KEYWORD_DETAIL = 'LOAD_NEWS_CLIPPING_KEYWORD_DETAIL';
export const LOAD_NEWS_CLIPPING_KEYWORD_DETAIL_ERROR = 'LOAD_NEWS_CLIPPING_KEYWORD_DETAIL_ERROR';
export const LOAD_NEWS_CLIPPING_KEYWORD_DETAIL_SUCCESS = 'LOAD_NEWS_CLIPPING_KEYWORD_DETAIL_SUCCESS';

export const LOAD_NEWS_CLIPPING_UPDATE_TONES = 'LOAD_NEWS_CLIPPING_UPDATE_TONES';
export const LOAD_NEWS_CLIPPING_UPDATE_TONES_ERROR = 'LOAD_NEWS_CLIPPING_UPDATE_TONES_ERROR';
export const LOAD_NEWS_CLIPPING_UPDATE_TONES_SUCCESS = 'LOAD_NEWS_CLIPPING_UPDATE_TONES_SUCCESS';

export const LOAD_NEWS_CLIPPING_DELETE_ARTICLE = 'LOAD_NEWS_CLIPPING_DELETE_ARTICLE';
export const LOAD_NEWS_CLIPPING_DELETE_ARTICLE_ERROR = 'LOAD_NEWS_CLIPPING_DELETE_ARTICLE_ERROR';
export const LOAD_NEWS_CLIPPING_DELETE_ARTICLE_SUCCESS = 'LOAD_NEWS_CLIPPING_DELETE_ARTICLE_SUCCESS';

export const LOAD_ISSUE_AUTO = 'LOAD_ISSUE_AUTO';
export const LOAD_ISSUE_AUTO_ERROR = 'LOAD_ISSUE_AUTO_ERROR';
export const LOAD_ISSUE_AUTO_SUCCESS = 'LOAD_ISSUE_AUTO_SUCCESS';
