export const LOAD_SEARCH = 'LOAD_SEARCH';
export const LOAD_SEARCH_SUCCESS = 'LOAD_SEARCH_SUCCESS';
export const LOAD_SEARCH_ERROR = 'LOAD_SEARCH_ERROR';

export const LOAD_SEARCH_MEDIA = 'LOAD_SEARCH_MEDIA';
export const LOAD_SEARCH_MEDIA_SUCCESS = 'LOAD_SEARCH_MEDIA_SUCCESS';
export const LOAD_SEARCH_MEDIA_ERROR = 'LOAD_SEARCH_MEDIA_ERROR';

export const LOAD_SEARCH_SUBCAT = 'LOAD_SEARCH_SUBCAT';
export const LOAD_SEARCH_SUBCAT_SUCCESS = 'LOAD_SEARCH_SUBCAT_SUCCESS';
export const LOAD_SEARCH_SUBCAT_ERROR = 'LOAD_SEARCH_SUBCAT_ERROR';

export const LOAD_SEARCH_CONTENT = 'LOAD_SEARCH_CONTENT';
export const LOAD_SEARCH_CONTENT_SUCCESS = 'LOAD_SEARCH_CONTENT_SUCCESS';
export const LOAD_SEARCH_CONTENT_ERROR = 'LOAD_SEARCH_CONTENT_ERROR';
