export const LOAD_SPOKEPERSON_LIST = 'LOAD_SPOKEPERSON_LIST';
export const LOAD_SPOKEPERSON_LIST_SUCCESS = 'LOAD_SPOKEPERSON_LIST_SUCCES';
export const LOAD_SPOKEPERSON_LIST_ERROR = 'LOAD_SPOKEPERSON_LIST_ERROR';

export const LOAD_SPOKEPERSON_DETAIL = 'LOAD_SPOKEPERSON_DETAIL';
export const LOAD_SPOKEPERSON_DETAIL_SUCCESS = 'LOAD_SPOKEPERSON_DETAIL_SUCCES';
export const LOAD_SPOKEPERSON_DETAIL_ERROR = 'LOAD_SPOKEPERSON_DETAIL_ERROR';

export const LOAD_SPOKEPERSON_TONE_UPDATE = 'LOAD_SPOKEPERSON_TONE_UPDATE';
export const LOAD_SPOKEPERSON_TONE_UPDATE_SUCCESS = 'LOAD_SPOKEPERSON_TONE_UPDATE_SUCCES';
export const LOAD_SPOKEPERSON_TONE_UPDATE_ERROR = 'LOAD_SPOKEPERSON_TONE_UPDATE_ERROR';

export const LOAD_SPOKEPERSON_STATISTIC = 'LOAD_SPOKEPERSON_STATISTIC';
export const LOAD_SPOKEPERSON_STATISTIC_SUCCESS = 'LOAD_SPOKEPERSON_STATISTIC_SUCCES';
export const LOAD_SPOKEPERSON_STATISTIC_ERROR = 'LOAD_SPOKEPERSON_STATISTIC_ERROR';

export const LOAD_SPOKEPERSON_STATISTIC_CLICK = 'LOAD_SPOKEPERSON_STATISTIC_CLICK';
export const LOAD_SPOKEPERSON_STATISTIC_CLICK_SUCCESS = 'LOAD_SPOKEPERSON_STATISTIC_CLICK_SUCCES';
export const LOAD_SPOKEPERSON_STATISTIC_CLICK_ERROR = 'LOAD_SPOKEPERSON_STATISTIC_CLICK_ERROR';

