export const LOAD_STOPWORD = 'LOAD_STOPWORD';
export const LOAD_STOPWORD_SUCCESS = 'LOAD_STOPWORD_SUCCESS';
export const LOAD_STOPWORD_ERROR = 'LOAD_STOPWORD_ERROR';

export const LOAD_STOPWORD_CREATE = 'LOAD_STOPWORD_CREATE';
export const LOAD_STOPWORD_CREATE_SUCCESS = 'LOAD_STOPWORD_CREATE_SUCCESS';
export const LOAD_STOPWORD_CREATE_ERROR = 'LOAD_STOPWORD_CREATE_ERROR';

export const LOAD_STOPWORD_DELETE = 'LOAD_STOPWORD_DELETE';
export const LOAD_STOPWORD_DELETE_SUCCESS = 'LOAD_STOPWORD_DELETE_SUCCESS';
export const LOAD_STOPWORD_DELETE_ERROR = 'LOAD_STOPWORD_DELETE_ERROR';

export const LOAD_STOPWORD_UPDATE = 'LOAD_STOPWORD_UPDATE';
export const LOAD_STOPWORD_UPDATE_SUCCESS = 'LOAD_STOPWORD_UPDATE_SUCCESS';
export const LOAD_STOPWORD_UPDATE_ERROR = 'LOAD_STOPWORD_UPDATE_ERROR';
