export const LOAD_CONFIG_SUBCAT_LIST = 'LOAD_CONFIG_SUBCAT_LIST';
export const LOAD_CONFIG_SUBCAT_LIST_SUCCESS = 'LOAD_CONFIG_SUBCAT_LIST_SUCCESS';
export const LOAD_CONFIG_SUBCAT_LIST_ERROR = 'LOAD_CONFIG_SUBCAT_LIST_ERROR';

export const LOAD_CONFIG_SUBCAT_CREATE = 'LOAD_CONFIG_SUBCAT_CREATE';
export const LOAD_CONFIG_SUBCAT_CREATE_SUCCESS = 'LOAD_CONFIG_SUBCAT_CREATE_SUCCESS';
export const LOAD_CONFIG_SUBCAT_CREATE_ERROR = 'LOAD_CONFIG_SUBCAT_CREATE_ERROR';

export const LOAD_CONFIG_SUBCAT_UPDATE = 'LOAD_CONFIG_SUBCAT_UPDATE';
export const LOAD_CONFIG_SUBCAT_UPDATE_SUCCESS = 'LOAD_CONFIG_SUBCAT_UPDATE_SUCCESS';
export const LOAD_CONFIG_SUBCAT_UPDATE_ERROR = 'LOAD_CONFIG_SUBCAT_UPDATE_ERROR';

export const LOAD_CONFIG_SUBCAT_DELETE = 'LOAD_CONFIG_SUBCAT_DELETE';
export const LOAD_CONFIG_SUBCAT_DELETE_SUCCESS = 'LOAD_CONFIG_SUBCAT_DELETE_SUCCESS';
export const LOAD_CONFIG_SUBCAT_DELETE_ERROR = 'LOAD_CONFIG_SUBCAT_DELETE_ERROR';

export const LOAD_CONFIG_SUBCAT_KEYWORD_LIST = 'LOAD_CONFIG_SUBCAT_KEYWORD_LIST';
export const LOAD_CONFIG_SUBCAT_KEYWORD_LIST_SUCCESS = 'LOAD_CONFIG_SUBCAT_KEYWORD_LIST_SUCCESS';
export const LOAD_CONFIG_SUBCAT_KEYWORD_LIST_ERROR = 'LOAD_CONFIG_SUBCAT_KEYWORD_LIST_ERROR';

export const LOAD_CONFIG_SUBCAT_KEYWORD_CREATE = 'LOAD_CONFIG_SUBCAT_KEYWORD_CREATE';
export const LOAD_CONFIG_SUBCAT_KEYWORD_CREATE_SUCCESS = 'LOAD_CONFIG_SUBCAT_KEYWORD_CREATE_SUCCESS';
export const LOAD_CONFIG_SUBCAT_KEYWORD_CREATE_ERROR = 'LOAD_CONFIG_SUBCAT_KEYWORD_CREATE_ERROR';

export const LOAD_CONFIG_SUBCAT_KEYWORD_DELETE = 'LOAD_CONFIG_SUBCAT_KEYWORD_DELETE';
export const LOAD_CONFIG_SUBCAT_KEYWORD_DELETE_SUCCESS = 'LOAD_CONFIG_SUBCAT_KEYWORD_DELETE_SUCCESS';
export const LOAD_CONFIG_SUBCAT_KEYWORD_DELETE_ERROR = 'LOAD_CONFIG_SUBCAT_KEYWORD_DELETE_ERROR';
