export const LOAD_WORD_CLOUD = 'LOAD_WORD_CLOUD';
export const LOAD_WORD_CLOUD_SUCCESS = 'LOAD_WORD_CLOUD_SUCCESS';
export const LOAD_WORD_CLOUD_ERROR = 'LOAD_WORD_CLOUD_ERROR';

export const LOAD_MED_COUNT_ARTICLE = 'LOAD_MED_COUNT_ARTICLE';
export const LOAD_MED_COUNT_ARTICLE_SUCCESS = 'LOAD_MED_COUNT_ARTICLE_SUCCESS';
export const LOAD_MED_COUNT_ARTICLE_ERROR = 'LOAD_MED_COUNT_ARTICLE_ERROR';

